// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: internal/api/myrpc/proto/main.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortenURLIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OriginalUrl string `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
}

func (x *ShortenURLIn) Reset() {
	*x = ShortenURLIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenURLIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLIn) ProtoMessage() {}

func (x *ShortenURLIn) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLIn.ProtoReflect.Descriptor instead.
func (*ShortenURLIn) Descriptor() ([]byte, []int) {
	return file_internal_api_myrpc_proto_main_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenURLIn) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type ShortenURLOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl string `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
}

func (x *ShortenURLOut) Reset() {
	*x = ShortenURLOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenURLOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLOut) ProtoMessage() {}

func (x *ShortenURLOut) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLOut.ProtoReflect.Descriptor instead.
func (*ShortenURLOut) Descriptor() ([]byte, []int) {
	return file_internal_api_myrpc_proto_main_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenURLOut) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type ShortenBatchIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ShortenBatchIn_ShortenBatchItemIn `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ShortenBatchIn) Reset() {
	*x = ShortenBatchIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenBatchIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchIn) ProtoMessage() {}

func (x *ShortenBatchIn) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchIn.ProtoReflect.Descriptor instead.
func (*ShortenBatchIn) Descriptor() ([]byte, []int) {
	return file_internal_api_myrpc_proto_main_proto_rawDescGZIP(), []int{2}
}

func (x *ShortenBatchIn) GetItems() []*ShortenBatchIn_ShortenBatchItemIn {
	if x != nil {
		return x.Items
	}
	return nil
}

type ShortenBatchOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ShortenBatchOut_ShortenBatchItemOut `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ShortenBatchOut) Reset() {
	*x = ShortenBatchOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenBatchOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchOut) ProtoMessage() {}

func (x *ShortenBatchOut) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchOut.ProtoReflect.Descriptor instead.
func (*ShortenBatchOut) Descriptor() ([]byte, []int) {
	return file_internal_api_myrpc_proto_main_proto_rawDescGZIP(), []int{3}
}

func (x *ShortenBatchOut) GetItems() []*ShortenBatchOut_ShortenBatchItemOut {
	if x != nil {
		return x.Items
	}
	return nil
}

type DeleteURLsIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls []string `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
}

func (x *DeleteURLsIn) Reset() {
	*x = DeleteURLsIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteURLsIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteURLsIn) ProtoMessage() {}

func (x *DeleteURLsIn) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteURLsIn.ProtoReflect.Descriptor instead.
func (*DeleteURLsIn) Descriptor() ([]byte, []int) {
	return file_internal_api_myrpc_proto_main_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteURLsIn) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

type DeleteURLsOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteURLsOut) Reset() {
	*x = DeleteURLsOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteURLsOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteURLsOut) ProtoMessage() {}

func (x *DeleteURLsOut) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteURLsOut.ProtoReflect.Descriptor instead.
func (*DeleteURLsOut) Descriptor() ([]byte, []int) {
	return file_internal_api_myrpc_proto_main_proto_rawDescGZIP(), []int{5}
}

type GetURLsIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetURLsIn) Reset() {
	*x = GetURLsIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetURLsIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLsIn) ProtoMessage() {}

func (x *GetURLsIn) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLsIn.ProtoReflect.Descriptor instead.
func (*GetURLsIn) Descriptor() ([]byte, []int) {
	return file_internal_api_myrpc_proto_main_proto_rawDescGZIP(), []int{6}
}

type GetURLsOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*GetURLsOut_GetURLsOutItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *GetURLsOut) Reset() {
	*x = GetURLsOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetURLsOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLsOut) ProtoMessage() {}

func (x *GetURLsOut) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLsOut.ProtoReflect.Descriptor instead.
func (*GetURLsOut) Descriptor() ([]byte, []int) {
	return file_internal_api_myrpc_proto_main_proto_rawDescGZIP(), []int{7}
}

func (x *GetURLsOut) GetItems() []*GetURLsOut_GetURLsOutItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type RedirectIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl string `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
}

func (x *RedirectIn) Reset() {
	*x = RedirectIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RedirectIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectIn) ProtoMessage() {}

func (x *RedirectIn) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectIn.ProtoReflect.Descriptor instead.
func (*RedirectIn) Descriptor() ([]byte, []int) {
	return file_internal_api_myrpc_proto_main_proto_rawDescGZIP(), []int{8}
}

func (x *RedirectIn) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type RedirectOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location string `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *RedirectOut) Reset() {
	*x = RedirectOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RedirectOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectOut) ProtoMessage() {}

func (x *RedirectOut) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectOut.ProtoReflect.Descriptor instead.
func (*RedirectOut) Descriptor() ([]byte, []int) {
	return file_internal_api_myrpc_proto_main_proto_rawDescGZIP(), []int{9}
}

func (x *RedirectOut) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type PingIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingIn) Reset() {
	*x = PingIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingIn) ProtoMessage() {}

func (x *PingIn) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingIn.ProtoReflect.Descriptor instead.
func (*PingIn) Descriptor() ([]byte, []int) {
	return file_internal_api_myrpc_proto_main_proto_rawDescGZIP(), []int{10}
}

type PingOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingOut) Reset() {
	*x = PingOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingOut) ProtoMessage() {}

func (x *PingOut) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingOut.ProtoReflect.Descriptor instead.
func (*PingOut) Descriptor() ([]byte, []int) {
	return file_internal_api_myrpc_proto_main_proto_rawDescGZIP(), []int{11}
}

type GetStatsIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetStatsIn) Reset() {
	*x = GetStatsIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatsIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsIn) ProtoMessage() {}

func (x *GetStatsIn) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsIn.ProtoReflect.Descriptor instead.
func (*GetStatsIn) Descriptor() ([]byte, []int) {
	return file_internal_api_myrpc_proto_main_proto_rawDescGZIP(), []int{12}
}

type GetStatsOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls  int64 `protobuf:"zigzag64,1,opt,name=urls,proto3" json:"urls,omitempty"`
	Users int64 `protobuf:"zigzag64,2,opt,name=users,proto3" json:"users,omitempty"`
}

func (x *GetStatsOut) Reset() {
	*x = GetStatsOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatsOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsOut) ProtoMessage() {}

func (x *GetStatsOut) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsOut.ProtoReflect.Descriptor instead.
func (*GetStatsOut) Descriptor() ([]byte, []int) {
	return file_internal_api_myrpc_proto_main_proto_rawDescGZIP(), []int{13}
}

func (x *GetStatsOut) GetUrls() int64 {
	if x != nil {
		return x.Urls
	}
	return 0
}

func (x *GetStatsOut) GetUsers() int64 {
	if x != nil {
		return x.Users
	}
	return 0
}

type ShortenBatchIn_ShortenBatchItemIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
}

func (x *ShortenBatchIn_ShortenBatchItemIn) Reset() {
	*x = ShortenBatchIn_ShortenBatchItemIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenBatchIn_ShortenBatchItemIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchIn_ShortenBatchItemIn) ProtoMessage() {}

func (x *ShortenBatchIn_ShortenBatchItemIn) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchIn_ShortenBatchItemIn.ProtoReflect.Descriptor instead.
func (*ShortenBatchIn_ShortenBatchItemIn) Descriptor() ([]byte, []int) {
	return file_internal_api_myrpc_proto_main_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ShortenBatchIn_ShortenBatchItemIn) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ShortenBatchIn_ShortenBatchItemIn) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type ShortenBatchOut_ShortenBatchItemOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ShortUrl      string `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
}

func (x *ShortenBatchOut_ShortenBatchItemOut) Reset() {
	*x = ShortenBatchOut_ShortenBatchItemOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenBatchOut_ShortenBatchItemOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchOut_ShortenBatchItemOut) ProtoMessage() {}

func (x *ShortenBatchOut_ShortenBatchItemOut) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchOut_ShortenBatchItemOut.ProtoReflect.Descriptor instead.
func (*ShortenBatchOut_ShortenBatchItemOut) Descriptor() ([]byte, []int) {
	return file_internal_api_myrpc_proto_main_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ShortenBatchOut_ShortenBatchItemOut) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ShortenBatchOut_ShortenBatchItemOut) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type GetURLsOut_GetURLsOutItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl    string `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl string `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
}

func (x *GetURLsOut_GetURLsOutItem) Reset() {
	*x = GetURLsOut_GetURLsOutItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetURLsOut_GetURLsOutItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLsOut_GetURLsOutItem) ProtoMessage() {}

func (x *GetURLsOut_GetURLsOutItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_myrpc_proto_main_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLsOut_GetURLsOutItem.ProtoReflect.Descriptor instead.
func (*GetURLsOut_GetURLsOutItem) Descriptor() ([]byte, []int) {
	return file_internal_api_myrpc_proto_main_proto_rawDescGZIP(), []int{7, 0}
}

func (x *GetURLsOut_GetURLsOutItem) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *GetURLsOut_GetURLsOutItem) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

var File_internal_api_myrpc_proto_main_proto protoreflect.FileDescriptor

var file_internal_api_myrpc_proto_main_proto_rawDesc = []byte{
	0x0a, 0x23, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d,
	0x79, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x0c,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x52, 0x4c, 0x49, 0x6e, 0x12, 0x21, 0x0a, 0x0c,
	0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x55, 0x72, 0x6c, 0x22,
	0x2c, 0x0a, 0x0d, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x52, 0x4c, 0x4f, 0x75, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x22, 0xb0, 0x01,
	0x0a, 0x0e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x49, 0x6e,
	0x12, 0x3e, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x49, 0x6e, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x1a, 0x5e, 0x0a, 0x12, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x21, 0x0a,
	0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x55, 0x72, 0x6c,
	0x22, 0xae, 0x01, 0x0a, 0x0f, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x4f, 0x75, 0x74, 0x12, 0x40, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x65, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4f, 0x75, 0x74, 0x2e, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x65, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x49, 0x74, 0x65, 0x6d, 0x4f, 0x75, 0x74, 0x52,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x59, 0x0a, 0x13, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65,
	0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x49, 0x74, 0x65, 0x6d, 0x4f, 0x75, 0x74, 0x12, 0x25, 0x0a,
	0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72,
	0x6c, 0x22, 0x22, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x52, 0x4c, 0x73, 0x49,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x04, 0x75, 0x72, 0x6c, 0x73, 0x22, 0x0f, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55,
	0x52, 0x4c, 0x73, 0x4f, 0x75, 0x74, 0x22, 0x0b, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c,
	0x73, 0x49, 0x6e, 0x22, 0x96, 0x01, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x4f,
	0x75, 0x74, 0x12, 0x36, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c,
	0x73, 0x4f, 0x75, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x4f, 0x75, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x50, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x55, 0x52, 0x4c, 0x73, 0x4f, 0x75, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1b, 0x0a, 0x09,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x72, 0x69,
	0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x55, 0x72, 0x6c, 0x22, 0x29, 0x0a, 0x0a,
	0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x29, 0x0a, 0x0b, 0x52, 0x65, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x4f, 0x75, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x08, 0x0a, 0x06, 0x50, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x22, 0x09, 0x0a, 0x07,
	0x50, 0x69, 0x6e, 0x67, 0x4f, 0x75, 0x74, 0x22, 0x0c, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x73, 0x49, 0x6e, 0x22, 0x37, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x4f, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x12, 0x52, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x12, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x32, 0xc6,
	0x02, 0x0a, 0x09, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x12, 0x37, 0x0a, 0x0a,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x52, 0x4c, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x52, 0x4c, 0x49, 0x6e, 0x1a,
	0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55,
	0x52, 0x4c, 0x4f, 0x75, 0x74, 0x12, 0x3d, 0x0a, 0x0c, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x65, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x49, 0x6e, 0x1a, 0x16, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x4f, 0x75, 0x74, 0x12, 0x37, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x52,
	0x4c, 0x73, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x55, 0x52, 0x4c, 0x73, 0x49, 0x6e, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x52, 0x4c, 0x73, 0x4f, 0x75, 0x74, 0x12, 0x2e, 0x0a,
	0x07, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x49, 0x6e, 0x1a, 0x11, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x4f, 0x75, 0x74, 0x12, 0x31, 0x0a,
	0x08, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x12, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x1a, 0x12, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x4f, 0x75, 0x74,
	0x12, 0x25, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x50, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x1a, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x50, 0x69, 0x6e, 0x67, 0x4f, 0x75, 0x74, 0x42, 0x1a, 0x5a, 0x18, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x79, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_api_myrpc_proto_main_proto_rawDescOnce sync.Once
	file_internal_api_myrpc_proto_main_proto_rawDescData = file_internal_api_myrpc_proto_main_proto_rawDesc
)

func file_internal_api_myrpc_proto_main_proto_rawDescGZIP() []byte {
	file_internal_api_myrpc_proto_main_proto_rawDescOnce.Do(func() {
		file_internal_api_myrpc_proto_main_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_api_myrpc_proto_main_proto_rawDescData)
	})
	return file_internal_api_myrpc_proto_main_proto_rawDescData
}

var file_internal_api_myrpc_proto_main_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_internal_api_myrpc_proto_main_proto_goTypes = []any{
	(*ShortenURLIn)(nil),                        // 0: proto.ShortenURLIn
	(*ShortenURLOut)(nil),                       // 1: proto.ShortenURLOut
	(*ShortenBatchIn)(nil),                      // 2: proto.ShortenBatchIn
	(*ShortenBatchOut)(nil),                     // 3: proto.ShortenBatchOut
	(*DeleteURLsIn)(nil),                        // 4: proto.DeleteURLsIn
	(*DeleteURLsOut)(nil),                       // 5: proto.DeleteURLsOut
	(*GetURLsIn)(nil),                           // 6: proto.GetURLsIn
	(*GetURLsOut)(nil),                          // 7: proto.GetURLsOut
	(*RedirectIn)(nil),                          // 8: proto.RedirectIn
	(*RedirectOut)(nil),                         // 9: proto.RedirectOut
	(*PingIn)(nil),                              // 10: proto.PingIn
	(*PingOut)(nil),                             // 11: proto.PingOut
	(*GetStatsIn)(nil),                          // 12: proto.GetStatsIn
	(*GetStatsOut)(nil),                         // 13: proto.GetStatsOut
	(*ShortenBatchIn_ShortenBatchItemIn)(nil),   // 14: proto.ShortenBatchIn.ShortenBatchItemIn
	(*ShortenBatchOut_ShortenBatchItemOut)(nil), // 15: proto.ShortenBatchOut.ShortenBatchItemOut
	(*GetURLsOut_GetURLsOutItem)(nil),           // 16: proto.GetURLsOut.GetURLsOutItem
}
var file_internal_api_myrpc_proto_main_proto_depIdxs = []int32{
	14, // 0: proto.ShortenBatchIn.items:type_name -> proto.ShortenBatchIn.ShortenBatchItemIn
	15, // 1: proto.ShortenBatchOut.items:type_name -> proto.ShortenBatchOut.ShortenBatchItemOut
	16, // 2: proto.GetURLsOut.items:type_name -> proto.GetURLsOut.GetURLsOutItem
	0,  // 3: proto.Shortener.ShortenURL:input_type -> proto.ShortenURLIn
	2,  // 4: proto.Shortener.ShortenBatch:input_type -> proto.ShortenBatchIn
	4,  // 5: proto.Shortener.DeleteURLs:input_type -> proto.DeleteURLsIn
	6,  // 6: proto.Shortener.GetURLs:input_type -> proto.GetURLsIn
	8,  // 7: proto.Shortener.Redirect:input_type -> proto.RedirectIn
	10, // 8: proto.Shortener.Ping:input_type -> proto.PingIn
	1,  // 9: proto.Shortener.ShortenURL:output_type -> proto.ShortenURLOut
	3,  // 10: proto.Shortener.ShortenBatch:output_type -> proto.ShortenBatchOut
	5,  // 11: proto.Shortener.DeleteURLs:output_type -> proto.DeleteURLsOut
	7,  // 12: proto.Shortener.GetURLs:output_type -> proto.GetURLsOut
	9,  // 13: proto.Shortener.Redirect:output_type -> proto.RedirectOut
	11, // 14: proto.Shortener.Ping:output_type -> proto.PingOut
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_api_myrpc_proto_main_proto_init() }
func file_internal_api_myrpc_proto_main_proto_init() {
	if File_internal_api_myrpc_proto_main_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_api_myrpc_proto_main_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ShortenURLIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_myrpc_proto_main_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ShortenURLOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_myrpc_proto_main_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ShortenBatchIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_myrpc_proto_main_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ShortenBatchOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_myrpc_proto_main_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteURLsIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_myrpc_proto_main_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteURLsOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_myrpc_proto_main_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetURLsIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_myrpc_proto_main_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetURLsOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_myrpc_proto_main_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*RedirectIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_myrpc_proto_main_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*RedirectOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_myrpc_proto_main_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*PingIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_myrpc_proto_main_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*PingOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_myrpc_proto_main_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*GetStatsIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_myrpc_proto_main_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*GetStatsOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_myrpc_proto_main_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*ShortenBatchIn_ShortenBatchItemIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_myrpc_proto_main_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*ShortenBatchOut_ShortenBatchItemOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_myrpc_proto_main_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*GetURLsOut_GetURLsOutItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_api_myrpc_proto_main_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_myrpc_proto_main_proto_goTypes,
		DependencyIndexes: file_internal_api_myrpc_proto_main_proto_depIdxs,
		MessageInfos:      file_internal_api_myrpc_proto_main_proto_msgTypes,
	}.Build()
	File_internal_api_myrpc_proto_main_proto = out.File
	file_internal_api_myrpc_proto_main_proto_rawDesc = nil
	file_internal_api_myrpc_proto_main_proto_goTypes = nil
	file_internal_api_myrpc_proto_main_proto_depIdxs = nil
}
